### PR TITLE
Support matching against package-qualified name as well

### LINKED ISSUE #11: Add way to limit patterns to a specific package
I'd like to create `reassign` rules that inform me if any stdlib globals are changed that shouldn't be, but I can't currently without worrying about many false positives. For example, one of the first symbols I'd like to check isn't modified is [`net/http.DefaultClient`](https://pkg.go.dev/net/http#DefaultClient). Now I have to specify the pattern `DefaultClient` but that can match a symbol defined in another package.

I'd like to be able to specify that I only want to check that `DefaultClient` from the `net/http` package hasn't been reassigned. It'd be hard to do with how matching is done currently, with one big regex checking many patterns. Maybe users could specify a list of patterns and if they contain literal periods everything after the last period would be the symbol pattern to match against, and everything before the last period would be the package pattern to match against?

### PR DESCRIPTION
**Pull request by chokoswitch**
Fixes #11

### CODE REVIEW

**Comment by chokoswitch** [comment]
@capnspacehook Thanks for the feature request, being able to match against package sounds useful. Would you be able to give this PR a brief check to make sure it accomplishes what you need? Thanks!

**Review by capnspacehook — CHANGES_REQUESTED** [review]
Looks pretty good overall, however I played around with the `packagepattern` test and found a case that failed: detecting reassignment of `net/http.DefaultClient` and `net/http.DefaultTransport` works fine, but detecting reassignment of a struct field doesn't: 

Adding this line to `testdata/packagepattern/src/a/a.go` will cause the test to fail:

```go
	myhttp.DefaultClient.Jar = nil // want "reassigning variable"
```

Also, I created a new test to check if dot imports are handled correctly which also failed. Go src file I placed in `testdata/dotimport/src/big/big.go`:

```go
package big

import (
	. "net/http"
)

func chungus() {
	DefaultClient = nil     // want "reassigning variable"
	DefaultClient.Jar = nil // want "reassigning variable"
}
```

**Comment by chokoswitch** [comment]
Thanks a lot for the check @capnspacehook those both look like great issues to fix. I'll go ahead and merge this one as it seems to not block those fixes.

It looks like you've given some thought into the implementations, would you be able to send a PR after I merge this one? Or otherwise I'll try to repro them myself too.

**Comment by capnspacehook** [comment]
👍 Makes sense.

I probably won't have time for a few weeks, but I can then. I'll let you know if I start working on it, otherwise go for it. Thanks for taking my feedback into consideration!

**Pull request merged**
